name: Build

on: [push, pull_request]

jobs:
  build-arm:
    runs-on: ubuntu-latest
    container: archlinux:latest

    steps:
    - name: Install Deps
      run: |
        pacman -Syu \
        arm-none-eabi-gcc arm-none-eabi-newlib arm-none-eabi-binutils \
        make \
        git --noconfirm

    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Check
      run: arm-none-eabi-gcc --version

    - name: Build
      run: cd stm32code/digital-lock && make GIT_SUBMODULES=true
  
  build-flutter:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
        cache: 'gradle'

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: stable

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3

    - name: Check
      run: flutter doctor
    
    - name: Get Deps
      run: cd client/digital_lock && flutter pub get
    
    - name: Build
      run: cd client/digital_lock && flutter build apk --debug -v
